### ISSUE TITLE
Missing Duotone

### ISSUE THREAD

**Issue by TomLewis** [ahmadeyamin/fontawesome-5-pro#4]
Regular, Solid & Light work fine, but none of the Duoptone Icons work. https://fontawesome.com/icons/microscope?style=duotone

**Comment by sayantan300** [comment]
It's because this is old... Current version is 5.10.1
@TomLewis 
@ahmadeyamin please update to the latest version.

**Comment by ahmadeyamin** [comment]
> It's because this is old... Current version is 5.10.1
> @TomLewis
> @ahmadeyamin please update to the latest version.

**Comment by ahmadeyamin** [comment]
I will try 😉

**Comment by sayantan300** [comment]
Thanks, do it ASAP!

**Comment by sayantan300** [comment]
I want 5.10.1+

**Comment by ahmadeyamin** [comment]
Version Updated now
