### ISSUE TITLE
Some files of version 5.0.13 not found

### ISSUE THREAD

**Issue by victornoletosysout** [ahmadeyamin/fontawesome-5-pro#5]
I can't use the plugin because some imports in **all.css** are not available in **webfonts**.

GET http://localhost:8000/assets/webfonts/pro-fa-duotone-900-5.0.13.woff2 net::ERR_ABORTED 404 (Not Found)
GET http://localhost:8000/assets/webfonts/pro-fa-solid-900-5.0.13.woff2 net::ERR_ABORTED 404 (Not Found)
GET http://localhost:8000/assets/webfonts/pro-fa-regular-400-5.0.13.woff2 net::ERR_ABORTED 404 (Not Found)
GET http://localhost:8000/assets/webfonts/pro-fa-duotone-900-5.0.13.woff net::ERR_ABORTED 404 (Not Found)
GET http://localhost:8000/assets/webfonts/pro-fa-solid-900-5.0.13.woff net::ERR_ABORTED 404 (Not Found)
GET http://localhost:8000/assets/webfonts/pro-fa-regular-400-5.0.13.woff net::ERR_ABORTED 404 (Not Found)
GET http://localhost:8000/assets/webfonts/pro-fa-duotone-900-5.0.13.ttf net::ERR_ABORTED 404 (Not Found)
GET http://localhost:8000/assets/webfonts/pro-fa-solid-900-5.0.13.ttf net::ERR_ABORTED 404 (Not Found)

**Comment by ahmadeyamin** [comment]
Thank You

**Comment by ahmadeyamin** [comment]
fixed now
